### PR TITLE
docs: add AH535

### PR DESCRIPTION
**Pull request by helgek**
added missing black color AH535

### CODE REVIEW

**Comment by Michsior14** [comment]
Do you know by any chance the device id for AH535? Also if you can update `info.md` it would be great.

**Comment by helgek** [comment]
Unfortunately not, I only have the AH510.

**Comment by Michsior14** [comment]
Ah! So it's not tested that it works? In general the devices are added to the readme once someone confirms it works and reports device id.

**Comment by helgek** [comment]
Correct, I had just assumed you may have forgotten to add it since it's only a colour variant of the AH530, so assuming it's the same data. But it might have a different device id of course to distinguish it from the AH530. I didn't check what this looks like for the other models.

**Comment by bhuebschen** [comment]
regarding the current version of the venta-app (2.1.1), the maximum device-id is 500 (id of AH500) if there is any device > 500, it will be detected as AH500

**Comment by bhuebschen** [comment]
> > regarding the current version of the venta-app (2.1.1), the maximum device-id is 500 (id of AH500) if there is any device > 500, it will be detected as AH500
> 
> Did you maybe find anything regarding the mentioned device in the app sources?

```
public static DeviceSeries SeriesFromModel(DeviceModelId deviceModelId)
{
	DeviceSeries result = DeviceSeries.Undefined;
	if (deviceModelId <= DeviceModelId.AS100)
	{
		if (deviceModelId - DeviceModelId.LP60 <= 5)
		{
			return DeviceSeries.AppControl;
		}
		if (deviceModelId - DeviceModelId.AP902 <= 2)
		{
			return DeviceSeries.Professional;
		}
		if (deviceModelId != DeviceModelId.AS100)
		{
			return result;
		}
	}
	else if (deviceModelId <= DeviceModelId.LP74)
	{
		if (deviceModelId - DeviceModelId.LW73 > 1 && deviceModelId - DeviceModelId.LP73 > 1)
		{
			return result;
		}
		return DeviceSeries.Aerostyle;
	}
	else if (deviceModelId != DeviceModelId.AS150)
	{
		if (deviceModelId != DeviceModelId.AH500)
		{
			return result;
		}
		return DeviceSeries.OriginalConnect;
	}
	result = DeviceSeries.AirSense;
	return result;
}

```

and the Enum i posted in my PR

**Comment by bhuebschen** [comment]
But i also found a lot of usefull informations in json-files that are bundles with the app .. these files contain properties of each device type including an description of the properties

**Comment by Michsior14** [comment]
> But i also found a lot of usefull informations in json-files that are bundles with the app .. these files contain properties of each device type including an description of the properties
> 
> I sent you an email with the files

Oh, those files are great help! Thanks. I see we made couple of assumptions that are completely wrong ;)

**Pull request merged**
