### PR TITLE
feat: support raw socket based devices

### LINKED ISSUE #5: Support for LW60
Is it possible to support the LW60 models?
I've been using OpenHAB intergration in HA to intergrate my LW60 [https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.ventaair](url)

### PR DESCRIPTION
**Pull request by Michsior14**
TODOs left:
- auto discovery of the V0 devices
- tests on real devices

Resolves #5

### CODE REVIEW

**Comment by EinzellerXD** [comment]
I basically tried a whole bunch of stuff today. I tried so much, that it blocked me and wouldn't respond for some time.
It turns out, that you only have to put Hash and DeviceName in the Header, for Complete and Action.
Also for the action it is easiest to just send, what changed, and only one thing at a time. If you try to change two things, it doesn't want to do it.
I don't know how much of this you can implement yourself, without having direct access to a device.
But there are quite a lot of bugs at the moment, because of the whole re implementation of the Protocols and so on.
But I can test and maybe implement the one or the other myself. There are also some Sensors missing, but one thing after the other.

grafik

**Comment by Michsior14** [comment]
@EinzellerXD In all cases except the mode change only one parameter is set per action. For mode I would probably need to know what params are needed for each of those:
- auto mode
- sleep mode
- fan level change

**Comment by EinzellerXD** [comment]
Ok
lets say, you want to switch from any mode (sleep, manual) to Automatic, you send:
`{"Header":{"Hash":"-42","DeviceName":"HomeAssistant"},"Action":{"Automatic":true}}`

the response is:
```
OK /Action
Content-Length: 371

{"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":65407,"DeviceName":""},"Action":{"Power":true,"FanSpeed":1,"TargetHum":50,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":true,"SysLanguage":0,"CleanLanguage":1,"TempUnit":0,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":3,"DelUser":false,"FiltLifetime":52800}}
```


then you want to change into sleep mode:
send:
`{"Header":{"Hash":"-42","DeviceName":"HomeAssistant"},"Action":{"SleepMode":true}}`

response:
```
OK /Action
Content-Length: 371

{"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":65503,"DeviceName":""},"Action":{"Power":true,"FanSpeed":1,"TargetHum":50,"Timer":0,"Boost":false,"SleepMode":true,"ChildLock":false,"Automatic":false,"SysLanguage":0,"CleanLanguage":1,"TempUnit":0,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":3,"DelUser":false,"FiltLifetime":52800}}
```

and then you want to change the fan speed:
`{"Header":{"Hash":"-42","DeviceName":"HomeAssistant"},"Action":{"FanSpeed":3}}`

response:
```
OK /Action
Content-Length: 371

{"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":65533,"DeviceName":""},"Action":{"Power":true,"FanSpeed":3,"TargetHum":50,"Timer":0,"Boost":false,"SleepMode":true,"ChildLock":false,"Automatic":false,"SysLanguage":0,"CleanLanguage":1,"TempUnit":0,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":3,"DelUser":false,"FiltLifetime":52800}}
```

it seems like, it is possible to change the fan speed, while the Humidifier is in SleepMode
but if it is in Automatic Mode, it will change to Automatic=false automatically:
`{"Header":{"Hash":"-42","DeviceName":"HomeAssistant"},"Action":{"FanSpeed":4}}`

response:
```
OK /Action
Content-Length: 372

{"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":65533,"DeviceName":""},"Action":{"Power":true,"FanSpeed":4,"TargetHum":50,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":false,"SysLanguage":0,"CleanLanguage":1,"TempUnit":0,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":3,"DelUser":false,"FiltLifetime":52800}}
```

**Comment by Michsior14** [comment]
@EinzellerXD Where you able to identify what else doesn't work?

**Comment by Michsior14** [comment]
> It's basically any combination of those if i try to send: `{"Header":{"Hash":"-42","DeviceName":"HomeAssistant"},"Action":{"FanSpeed":1,"Automatic":false}}` which would be correct, because i try to change the fan speed and, in this case the automatic was off already it results in:
> 
> ```
> NOK /Action
> Content-Length: 372
> 
> {"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":65405,"DeviceName":""},"Action":{"Power":true,"FanSpeed":4,"TargetHum":50,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":false,"SysLanguage":0,"CleanLanguage":1,"TempUnit":0,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":3,"DelUser":false,"FiltLifetime":52800}}
> ```
> 
> it's the same for eg. SleepMode:true and Automatic:false or vise versa.
> 
> If you could fit that in, if it works with the other humidifiers too, you could try to refresh the state of the humidifier in HA, with the response you get from the Humidifier after an action, because regardless if it was OK or NOK, it tells you the current state.

Ok, now it should be separate action. Please give it a try if you can.

**Comment by Michsior14** [comment]
@EinzellerXD Please try again, I've also re-added the custom protocol dropdown during the setup if needed (not translations won't work there due to lokalize pipeline that's executed on main).

**Pull request merged**
